# Labels based on description/body keywords for Issues and PRs

# Type of Change
enhancement:
  - /feature/i
  - /feature request/i
  - /enhancement/i
  - /proposal/i
  - /add/i
  - /improve/i
  - /extend/i
  - /create/i
  - /new/i
  - /implement/i
  - /allow/i

bug:
  - /bug/i
  - /fix/i
  - /issue/i
  - /error/i
  - /fail/i
  - /crash/i
  - /broken/i
  - /exception/i

research:
  - /research/i
  - /experimental/i
  - /investigation/i
  - /study/i
  - /analysis/i

documentation:
  - /docs/i
  - /documentation/i
  - /typo/i
  - /readme/i

question:
  - /question/i
  - /how to/i
  - /help/i
  - /clarification/i

# Website/Frontend/Backend
website:
  - /website/i
  - /web page/i
  - /web app/i
  - /iris-website/i

frontend:
  - /frontend/i
  - /ui/i
  - /user interface/i
  - /component/i
  - /react/i
  - /next\.js/i
  - /button/i
  - /page/i

backend:
  - /backend/i
  - /api/i
  - /endpoint/i
  - /server/i
  - /flask/i
  - /route/i

# Specific Topics
size:
  - /passformer_binary_size/i
  - /binary size/i
  - /code size/i

runtime:
  - /passformer_runtime/i
  - /execution time/i
  - /performance/i
  - /latency/i

dependencies:
  - /pip/i
  - /install/i
  - /requirements/i
  - /setup/i
  - /dependency/i
  - /package/i
  - /env/i

model:
  - /model/i
  - /training/i
  - /inference/i
  - /weights/i

# Code related
compiler:
  - /compile/i
  - /llvm/i
  - /clang/i
  - /optimization/i
  - /pass/i
  - /pass sequence/i

